### ISSUE TITLE
Rename to opensearch-common-utils

### ISSUE THREAD

**Issue by dblock** [opensearch-project/common-utils#13]
**Is your feature request related to a problem? Please describe.**
To be consistent with every other library, rename to `opensearch-common-utils`.

**Comment by lezzago** [comment]
@dblock is this something we want to do currently? This would be a breaking change, so we would need a plan to ensure consumers are notified of this and will have to label this for 3.0.

**Comment by dblock** [comment]
I'll close, this is very old.
