### ISSUE TITLE
Maintainers list cleanup process

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/common-utils#141]
Today all the packages in opensearch-project such as [common-utils](https://github.com/opensearch-project/common-utils) have the list of maintainers which is controlled by the [MAINTAINERS.md](https://github.com/opensearch-project/common-utils/blob/main/MAINTAINERS.md) file. We do have process defined by how we add people to the maintainers list depending upon their contributions and engagement in reviewing PRs, triaging issues etc. 

However, this doesn’t necessarily imply that ``MAINTAINERS.md`` becomes the ever growing list of maintainers. We should come  up with some unified process around cleaning up the list, based on the recency of the activities of the maintainers. Such as inactivity for 60 days. 

Opening up this issue to collect more feedback/thoughts. Also to know, if we have already given some thought to it previously.

**Comment by lezzago** [comment]
Is 60 days sufficient or should we possibly consider 90 days for repos like this as typically there are not many changes going in. Also I think inactivity should mean they do not push commits, review PRs, add github issues, or coment on github issues.

**Comment by getsaurabh02** [comment]
This has been later discussed broadly as part of https://github.com/opensearch-project/.github/pull/59.
The new proposal should apply to all the OpenSearch Repositories.
