### ISSUE TITLE
[Issue]: Add code coverage badge to README.md, .codecov.yml with require_ci_to_pass: yes

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/common-utils#157]
Add code coverage badge and add the following for ci to pass, call it from GitHub Actions

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"
  status:
    project:
      default:
        target: 75%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target

**Comment by engechas** [comment]
Closing as resolved by #171
