### ISSUE TITLE
Ensure common-utils can be a drop-in replacement for job-scheduler working in ODFE 1.13 and ES 7.10.x for v1.0.0

### ISSUE THREAD

**Issue by dblock** [opensearch-project/common-utils#19]
Coming from [opensearch-plugins#12](https://github.com/opensearch-project/opensearch-plugins/issues/12), enable upgrade to OpenSearch, while supporting backward compatibility.

- [x] Rename Namespaces (e.g. `com.amazon.opendistroforelasticsearch` to `org.opensearch`)
- [x] Rename Classes, Methods, Variables 
- [x] Rename Remaining Identifiers (e.g. `Opendistro` to `OpenSearch`).
- [ ] Rename, and Backwards Compatibility for Rest APIs
- [ ] Rename, and Backwards Compatibility for Settings 
- [ ] Rename, and Backwards Compatibility for Indices
- [ ] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ES 7.10.x cluster 
- [ ] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ODFE 1.13.x cluster 
- [ ] Drop in replacement for the Opendistro version 1.13 of the plugin

**Comment by VachaShah** [comment]
Renaming of the namespaces, classes, variables, methods and identifiers is done to reflect OpenSearch. There are some settings and APIs being used from security which need to be updated once security-plugin comes in with the update. I have opened an issue for this: #22. 

For the above checklist, the remaining part is the update in `CI.yml` to required OpenSearch version.

**Comment by dblock** [comment]
@VachaShah What else needs to be done for this, or can it be closed?

**Comment by VachaShah** [comment]
@dblock Looks like all the required items are complete for this, it can be closed.
