### ISSUE TITLE
Add this repo to core's version.properties for plugins to have seamless access

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/common-utils#205]
Security plugin (among other plugins) uses common_utils_version to get common-utils version dynamically based on opensearch-build's version.
```
opensearch_version = System.getProperty("opensearch.version", "2.2.0-SNAPSHOT")
version_tokens = opensearch_version.tokenize('-')
opensearch_build = version_tokens[0] + '.0'
common_utils_version = System.getProperty("common_utils.version", opensearch_build);
```
This is breaking the build because build.gradle is expecting common-utils to be available with version 2.2.0.0 but it is not out yet. This will block PRs from getting merged. A temporary solution to fix this is to hard-code `common_utils_version` property to latest stable version.

_Proposed Solution_:
Since hard-coding is not a good practice, and other plugins might be similarly affected by this issue, common-utils version should be added to [version.properties](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties) file in core, to enable other plugins to easily access this dependency in build.gradle using something like:
```
testImplementation "org.opensearch:common-utils:${versions.common_utils}"
```
And common-utils can create a PR against core to update the core's version.properties each time there is a new release.

**Comment by dblock** [comment]
Common-utils version cannot be added in core because it depends on core, and it would be a chicken-and-egg problem. 

Since you have a dependency on common-utils and all versions must match, I think the right thing to do is to wait for common-utils to increment its version and publish a SNAPSHOT. You can always PR that here when you find yourself in that situation.
