### ISSUE TITLE
[FEATURE]Refactor data model migration from alerting to common-utils

### ISSUE THREAD

**Issue by sbcd90** [opensearch-project/common-utils#236]
**Is your feature request related to a problem?**

This is a follow-up issue created for PR #227 .

The issue is mainly created to check if heavy objects moved to `common-utils` as part of #227 can still be re-modeled as lightweight pojos  to further decouple the logic from `alerting` plugin.

**Comment by engechas** [comment]
Closing as completed by alerting 556
