### ISSUE TITLE
[BUG] Names don't adhere to plugin naming convention 

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/common-utils#330]
**What is the bug?**
Align all names to the convention: 
https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#opensearch-plugins

We should adjust the folder and move build.gradle, etc. to the root folder of the repo.

[opensearchplugin metadata is missing from build.gradle](https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#metadata)

**Do you have any additional context?**
Referred to here:
https://github.com/opensearch-project/opensearch-plugins/issues/174

**Comment by lezzago** [comment]
@mnkugler this is not a plugin and is used as a common jar library for other plugins to use.

**Comment by mnkugler** [comment]
@lezzago thanks for clarifying. @wbeckler closed the ticket.
