### ISSUE TITLE
Move common-utils to OpenSearch core: Enable integration tests

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/common-utils#345]
Meta issue: Move [common-utils to OpenSearch core](https://github.com/opensearch-project/OpenSearch/issues/2545#issuecomment-1076378627)

1. The [Integration Tests are Disabled](https://github.com/opensearch-project/common-utils/blob/d77dec5a69e9f99c2948a06d088b505e5fa1dd7e/src/test/java/org/opensearch/commons/rest/IntegrationTests.java#L29) . Enable integration tests.

**Comment by lezzago** [comment]
There are no integration tests for common-utils as its a library and it doesn't make sense to create integration tests for the package.
