### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/common-utils#368]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the Common Utils repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Common Utils | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | Certificate or Origin | https://github.com/opensearch-project/common-utils/issues/368 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by AWSHurneyt** [comment]
Your findings look correct.

**Comment by engechas** [comment]
Hi @scrawfor99 - can this issue be resolved now or is there expected an expected action we should take before resolving this issue?
