### ISSUE TITLE
Support ISM publishing notifications to notification plugin with pass through API

### ISSUE THREAD

**Issue by dbbaughe** [opensearch-project/common-utils#44]
**Is your feature request related to a problem? Please describe.**
https://github.com/opensearch-project/notifications/issues/253

Adding the legacy classes/request/response/etc. needed for ISM to publish legacy notifications.

**Comment by getsaurabh02** [comment]
With https://github.com/opensearch-project/common-utils/pull/53 being merged, don't see any pending action items here.
