### ISSUE TITLE
Support inject tenant in InjectSecurity

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/common-utils#51]
**Is your feature request related to a problem? Please describe.**
https://github.com/opensearch-project/common-utils/blob/bafe9aa674bc356cf129c81802a953976798c376/src/main/java/org/opensearch/commons/InjectSecurity.java#L114
Currently `InjectSecurity` only supports injecting roles and users, and notifications issue https://github.com/opensearch-project/notifications/issues/244 might need support for tenants.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by getsaurabh02** [comment]
Closing since we support backend roles instead of tenants now.
