### ISSUE TITLE
Generate and upload code coverage report through CI workflow

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/common-utils#61]
**Is your feature request related to a problem? Please describe.**
https://github.com/opensearch-project/opensearch-plugins/issues/73

**Describe the solution you'd like**
Please update the CI workflow to generate code coverage and upload it to Codecov, so that the code coverage information is shown in the Codecov dashboard (https://app.codecov.io/gh/opensearch-project/)

**Describe alternatives you've considered**
N/A

**Additional context**
The guide for reporting the code coverage is located here. (https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#code-coverage-reporting)

**Comment by engechas** [comment]
Codevoc CI is present, closing
