### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by dblock** [opensearch-project/common-utils#86]
**Is your feature request related to a problem? Please describe.**
Coming from https://github.com/opensearch-project/opensearch-build/issues/33

**Describe the solution you'd like**
Add Windows CI for this repo.

**Comment by engechas** [comment]
Looks like windows CI was added a while back: https://github.com/opensearch-project/common-utils/blob/main/.github/workflows/ci.yml#L53. Closing, please reopen if the requirement is not satisfied
