### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/common-utils#89]
Coming from [opensearch-build#567](https://github.com/opensearch-project/opensearch-build/issues/567), release version 1.2. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update the Public Roadmap.
- [x] Create, update, triage and label all features and issues targeted for this release with v1.2.0. 

### CI/CD

- [x] Increment version on main to `1.2.0.0`.
- [x] Ensure working and passing CI.
- [x] Re(add) this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).

### Pre-Release

- [x] Branch and build from a `1.2` branch.
- [x] Update your branch in the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).
- [x] Feature complete, pencils down.
- [x] Fix bugs that target this release.

### Release

- [x] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Gather, review and publish release notes.
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release

- [x] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [ ] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-plugins/templates/release.md).
- [ ] Conduct a postmortem, and publish its results.

**Comment by peternied** [comment]
Note; only outstanding change currently in this repo is https://github.com/opensearch-project/common-utils/pull/83 which looks specific for notifications.  I'll operate as the defacto owner until we can get someone better suited

**Comment by peternied** [comment]
@lezzago Are there any additional issues/PRs that need to have the `v1.2.0` tag applied? If not, then you can close out all the preparation tasks.

**Comment by lezzago** [comment]
@peternied There are no more PRs that need `v1.2.0` tag on them. I have closed out all the preparation tasks.

**Comment by dblock** [comment]
I see a lot of issues in https://github.com/opensearch-project/common-utils/issues that are untriaged.

**Comment by peternied** [comment]
@lezzago Until Friday the 12th at noon PST, any tests that use distribution downloader were running against old bits and need to be rerun.  Can you please see if your team was impacted, rerun the tests, and then mark the tests run as completed in https://github.com/opensearch-project/opensearch-build/issues/954?

**Comment by lezzago** [comment]
@peternied, I am not able to mark the test as completed in the issue, can you please do it for me? The tests did not have any issues.

**Comment by dblock** [comment]
1.2 has shipped a long time ago, closing
